GET http://localhost:8565/expenses

<> 2023-06-05T202344.200.json
<> 2023-06-05T200136.200.json
<> 2023-06-05T194759.200.txt

###
POST http://localhost:8565/expenses
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBdXRoZW50aWNhdGlvbiIsImlzcyI6Imh0dHA6Ly8wLjAuMC4wOjgwODAvIiwidXNlckVtYWlsIjoiY2NodW5kdXJpQGVtYWlsLmNvbSIsImV4cCI6MTY4Njg0NTk2NH0.hfp_foeKzYNCABFBCp4lKuE4coZKc-VvGdxOBwo47eg

{
  "description": "Burger with Pomes",
  "amount": "16",
  "category": "Beauty",
  "place": "Burger King"
}

###
POST http://localhost:8565/users
content-type: application/json

{
  "name": "Chaitanya",
  "age": "30",
  "userName": "cchunduri",
  "password": "pass",
  "email": "cchunduri@email.com"
}

###
GET http://localhost:8565/users/cchunduri@email.com
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBdXRoZW50aWNhdGlvbiIsImlzcyI6Imh0dHA6Ly8wLjAuMC4wOjgwODAvIiwidXNlcklkIjoiY2NodW5kdXJpQGVtYWlsLmNvbSIsImV4cCI6MTY4NjIyNjU3NH0.7DtU5jHtChPzU7AstimIwiNXEGnHHxWvUTs8_m9TZ8Q

###
POST http://localhost:8565/login/
content-type: application/json

{
  "email": "cchunduri@email.com",
  "password": "pass"
}

###
GET http://localhost:8565/users/cchunduri@email.com/expenses
content-type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiJBdXRoZW50aWNhdGlvbiIsImlzcyI6Imh0dHA6Ly8wLjAuMC4wOjgwODAvIiwidXNlckVtYWlsIjoiY2NodW5kdXJpQGVtYWlsLmNvbSIsImV4cCI6MTY4Njg0NTk2NH0.hfp_foeKzYNCABFBCp4lKuE4coZKc-VvGdxOBwo47eg