ktor:
  application:
    modules:
      - com.cchunduri.ApplicationKt.module
  deployment:
    port: 8080
  development: true

postgres:
  url: "jdbc:postgres://$USERNAME:$PASSWORD@$HOSTNAME:$PORT/$DATABASE"
  user: "$USERNAME"
  password: "$PASSWORD"

jwt:
  secret: "expense-manager-jwt-sec"
  issuer: "http://0.0.0.0:8080/"
  audience: "http://0.0.0.0:8080/hello"
  realm: "Access to 'expenses'"
  validity: 86400000